/*
 * This file is generated by jOOQ.
*/
package com.example.demo.db;


import com.example.demo.db.tables.Faq;
import com.example.demo.db.tables.SchemaVersion;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Spring extends SchemaImpl {

    private static final long serialVersionUID = -788355108;

    /**
     * The reference instance of <code>spring</code>
     */
    public static final Spring SPRING = new Spring();

    /**
     * The table <code>spring.faq</code>.
     */
    public final Faq FAQ = com.example.demo.db.tables.Faq.FAQ;

    /**
     * The table <code>spring.schema_version</code>.
     */
    public final SchemaVersion SCHEMA_VERSION = com.example.demo.db.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * No further instances allowed
     */
    private Spring() {
        super("spring", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.FAQ_FAQ_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Faq.FAQ,
            SchemaVersion.SCHEMA_VERSION);
    }
}
