/*
 * This file is generated by jOOQ.
*/
package com.example.demo.db;


import com.example.demo.db.tables.Faqs;
import com.example.demo.db.tables.SchemaVersion;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.faqs</code>.
     */
    public static final Faqs FAQS = com.example.demo.db.tables.Faqs.FAQS;

    /**
     * The table <code>public.schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = com.example.demo.db.tables.SchemaVersion.SCHEMA_VERSION;
}
