/*
 * This file is generated by jOOQ.
*/
package com.example.demo.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Faq implements Serializable {

    private static final long serialVersionUID = 1593808412;

    private final Integer   faqId;
    private final String    title;
    private final String    question;
    private final String    answer;
    private final Integer   version;
    private final Timestamp updatedTime;
    private final Timestamp createdTime;

    public Faq(Faq value) {
        this.faqId = value.faqId;
        this.title = value.title;
        this.question = value.question;
        this.answer = value.answer;
        this.version = value.version;
        this.updatedTime = value.updatedTime;
        this.createdTime = value.createdTime;
    }

    public Faq(
        Integer   faqId,
        String    title,
        String    question,
        String    answer,
        Integer   version,
        Timestamp updatedTime,
        Timestamp createdTime
    ) {
        this.faqId = faqId;
        this.title = title;
        this.question = question;
        this.answer = answer;
        this.version = version;
        this.updatedTime = updatedTime;
        this.createdTime = createdTime;
    }

    public Integer getFaqId() {
        return this.faqId;
    }

    public String getTitle() {
        return this.title;
    }

    public String getQuestion() {
        return this.question;
    }

    public String getAnswer() {
        return this.answer;
    }

    public Integer getVersion() {
        return this.version;
    }

    public Timestamp getUpdatedTime() {
        return this.updatedTime;
    }

    public Timestamp getCreatedTime() {
        return this.createdTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Faq (");

        sb.append(faqId);
        sb.append(", ").append(title);
        sb.append(", ").append(question);
        sb.append(", ").append(answer);
        sb.append(", ").append(version);
        sb.append(", ").append(updatedTime);
        sb.append(", ").append(createdTime);

        sb.append(")");
        return sb.toString();
    }
}
