/*
 * This file is generated by jOOQ.
*/
package com.example.demo.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Faqs implements Serializable {

    private static final long serialVersionUID = -364344453;

    private final Integer   id;
    private final String    title;
    private final String    content;
    private final Integer   version;
    private final Timestamp updatedTime;
    private final Timestamp createdTime;

    public Faqs(Faqs value) {
        this.id = value.id;
        this.title = value.title;
        this.content = value.content;
        this.version = value.version;
        this.updatedTime = value.updatedTime;
        this.createdTime = value.createdTime;
    }

    public Faqs(
        Integer   id,
        String    title,
        String    content,
        Integer   version,
        Timestamp updatedTime,
        Timestamp createdTime
    ) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.version = version;
        this.updatedTime = updatedTime;
        this.createdTime = createdTime;
    }

    public Integer getId() {
        return this.id;
    }

    public String getTitle() {
        return this.title;
    }

    public String getContent() {
        return this.content;
    }

    public Integer getVersion() {
        return this.version;
    }

    public Timestamp getUpdatedTime() {
        return this.updatedTime;
    }

    public Timestamp getCreatedTime() {
        return this.createdTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Faqs (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(content);
        sb.append(", ").append(version);
        sb.append(", ").append(updatedTime);
        sb.append(", ").append(createdTime);

        sb.append(")");
        return sb.toString();
    }
}
